services:
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog/backend:latest
    container_name: stagelog-api
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "80:8000"
    command: >
          bash -lc "python manage.py collectstatic --noinput &&
          python manage.py migrate &&
          gunicorn --bind 0.0.0.0:8000 config.wsgi:application
          --access-logfile -
          --error-logfile -
          --log-level debug
          --capture-output
          --timeout 120"
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /aws/ec2/stagelog-backend
        awslogs-create-group: "true"
